theme: jekyll-theme-architect

title: [Java EE Platform Specification]
description: [Project for the Java EE Expert Group]

# sidebar links url
links:
  download: https://github.com/javaee/javaee-spec/tree/master
  source: https://github.com/javaee/javaee-spec
  license: LICENSE
  issues_url: site.github.issues_url # project's issue tracker
  #mailinglist:
  #javadocs:
  #docs:
  #faq:

